function Heart_GUI_preset(outputs)
% Copyright 2025 Ben Allen.
% This program is released under license GPL version 3.
close all
%% GUI
global outputs
global ConfigGUI
%% Get the display
pos = get(0, 'screensize'); %get the screensize
W=0.8*pos(3);
H=0.8*pos(4);
x0=50;
y0=50;
WIDTH=W-50-x0;
HEIGHT=H-100-y0;
%[left bottom width height],the most outer frame
ConfigGUI.Handle=figure('Units', 'Pixels', 'Position', [x0 y0 WIDTH HEIGHT],...
    'Resize','off','Name','Heart Model Set up','NumberTitle','Off',...
    'Tag','GUI');
% General model settings
ConfigGUI.model_settings = uipanel('Parent',ConfigGUI.Handle,...
    'Units','normalized',...
    'Position',[0.05 0.25 0.45 0.65],...
    'Title','General Model Settings',...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'HandleVisibility','callback',...
    'Tag','modelPanel');
% Pacemaker specific settings
ConfigGUI.pacemaker_settings = uipanel('Parent',ConfigGUI.Handle,...
    'Units','normalized',...
    'Position',[0.5 0.25 0.45 0.65],...
    'Title','Pacemaker Settings',...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'HandleVisibility','callback',...
    'Tag','pacemakerPanel');


% Parameter settings --- Drop Down
% parasMulti:
% Bradycardia+AV block+premature ventricular complex (PVC), RBBB (slow velocity):
% % SA BCL=1400; the automaticity of Node 24 (RBB) enabled (para48=0); path 10 backward enabled (para7=1.0); Path 15 cv=0.04, path 27 cv=0.4; 
% parasMulti2: PVC introduces PMT
% Bradycardia+AV block+premature ventricular complex (PVC), RBBB (complete blockage, i.e.,cv=0):
% % SA BCL=1400; the automaticity of Node 24 (RBB) enabled (para48=0); path 10 backward enabled (para7=1.0); Path 15 cv=0.04, path 27 cv=0;
% parasMulti3: extra VP introduces AVNRT
% % SA BCL=814; CS BCL=1194 enabled (para48=0); path 10 backward enabled (para7=0.8); ppR5
% cfg=[814,1194,2,0,0.100000000000000,0.250000000000000,278,0.0146200000000000,0.00872000000000000,2300,2,1,0.100000000000000,0.250000000000000,1.100000000000000,0.0700000000000000,0.0700000000000000,0.0700000000000000,0.0700000000000000];
%%parasNormal Normal but slight AV delay compared to device AVI.
% Node Attribute type

uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.8 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Parameter choice:',...
    'HandleVisibility','callback');
ConfigGUI.parameterchoice = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.3 0.8 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'Normal', 'parasMulti', 'parasMulti2', 'parasMulti3'},...
    'HandleVisibility','callback',...
    'Tag','paramchoice');

% Whether to edit the existing model structure (opens the Heart Editing GUI after this one closes)
ConfigGUI.editmodel = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',[0.05 0.0 0.35 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Edit Model Network',...
    'HandleVisibility','callback',...
    'Tag','editmodel');

uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.6 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Plot 1:',...
    'HandleVisibility','callback');
uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.5 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Plot 2:',...
    'HandleVisibility','callback');
uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.4 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Plot 3:',...
    'HandleVisibility','callback');
uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.3 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Plot 4:',...
    'HandleVisibility','callback');
uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.2 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Plot 5:',...
    'HandleVisibility','callback');
uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',[0.05 0.1 0.1 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String','Plot 6:',...
    'HandleVisibility','callback');
ConfigGUI.plot0 = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.15 0.6 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'AEGM', 'None', 'VEGM', 'Aget/Vget', 'AP/VP', 'AS/VS', 'AR/VR'},...
    'HandleVisibility','callback');
ConfigGUI.plot1 = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.15 0.5 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'VEGM', 'None', 'AEGM', 'Aget/Vget', 'AP/VP', 'AS/VS', 'AR/VR'},...
    'HandleVisibility','callback');
ConfigGUI.plot2 = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.15 0.4 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'Aget/Vget', 'None','AEGM', 'VEGM',  'AP/VP', 'AS/VS', 'AR/VR'},...
    'HandleVisibility','callback');
ConfigGUI.plot3 = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.15 0.3 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'AP/VP', 'None', 'AEGM', 'VEGM', 'Aget/Vget',  'AS/VS', 'AR/VR'},...
    'HandleVisibility','callback');
ConfigGUI.plot4 = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.15 0.2 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{'AS/VS','None', 'AEGM', 'VEGM', 'Aget/Vget', 'AP/VP',  'AR/VR'},...
    'HandleVisibility','callback');
ConfigGUI.plot5 = uicontrol('Parent',ConfigGUI.model_settings,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.15 0.1 0.25 0.15],...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'String',{ 'AR/VR', 'None', 'AEGM', 'VEGM', 'Aget/Vget', 'AP/VP', 'AS/VS'},...
    'HandleVisibility','callback');



ConfigGUI.closebutton = uicontrol('Parent',ConfigGUI.Handle,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',[0.25 0.05 0.5 0.15],...
    'String','Close this GUI with the current settings on display',...
    'BackgroundColor',get(ConfigGUI.Handle,'Color'),...
    'HandleVisibility','callback',...
    'Callback',@closeGUI,...
    'Tag','closeButton');
waitfor(ConfigGUI.Handle);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function closeGUI(hObject,eventdata)
outputs.plot0 = ConfigGUI.plot0.String{ConfigGUI.plot0.Value};
outputs.plot1 = ConfigGUI.plot1.String{ConfigGUI.plot1.Value};
outputs.plot2 = ConfigGUI.plot2.String{ConfigGUI.plot2.Value};
outputs.plot3 = ConfigGUI.plot3.String{ConfigGUI.plot3.Value};
outputs.plot4 = ConfigGUI.plot4.String{ConfigGUI.plot4.Value};
outputs.plot5 = ConfigGUI.plot5.String{ConfigGUI.plot5.Value};
outputs.param = ConfigGUI.parameterchoice.String{ConfigGUI.parameterchoice.Value};
outputs.editmodel = ConfigGUI.editmodel.Value;
close all

end
% Anymore model settings?
% Pacemaker Settings
% Whether to have a pacemaker at all in the modelling
% decides whether to use the rest of this GUI section
% What type of pacemaker 
% DDT
% Dual chamber/single chamber
% Resp Modulation (future work)
end